steps:

  - command: |
      bash .scripts/artifactory.sh -e ${BUILDKITE_BRANCH} && gradle assemble artifactoryPublish
    branches: master develop release/* feature/*
    label: "Build & Publish Library"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      bash .scripts/artifactory.sh -e scratch && gradle assemble artifactoryPublish
    branches: "!master" "!develop" "!release/*" "!feature/*"
    label: "Build & Publish Library"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      bash .scripts/artifactory.sh -e scratch && gradle test
    branches: "!master" "!develop" "!release/*" "!feature/*"  
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

    - command: |
      bash .scripts/artifactory.sh -e ${BUILDKITE_BRANCH} && gradle test
    branches: master develop release/* feature/*
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"