steps:

  - command: |
      if [[ ${BUILDKITE_BRANCH} == "develop" || ${BUILDKITE_BRANCH} == "master" || ${BUILDKITE_BRANCH} == "release/*" || ${BUILDKITE_BRANCH} == "feature/*" ]]; then 
        bash .scripts/artifactory.sh -e ${BUILDKITE_BRANCH} && gradle assemble artifactoryPublish
      else
        bash .scripts/artifactory.sh -e scratch && gradle assemble artifactoryPublish
      fi
    label: "Build & Publish Library"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      if [[ ${BUILDKITE_BRANCH} == "develop" || ${BUILDKITE_BRANCH} == "master" || ${BUILDKITE_BRANCH} == "release/*" || ${BUILDKITE_BRANCH} == "feature/*" ]]; then 
        bash .scripts/artifactory.sh -e ${BUILDKITE_BRANCH} && gradle test
      else
        bash .scripts/artifactory.sh -e scratch && gradle test
      fi
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"