steps:
  - command: |
      gradle build
    label: "Build Library"
    agents:
     - "queue=automation-android-builder-fleet"
    artifact_paths:
      - "./app/build/outputs/apk/debug/*.apk"

  - wait

  - command: |
      gradle test
    label: "Run Tests"
    agents:
     - - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"