steps:
  - command: |
    .scripts/artifactory_properties.sh"  
    label: "Set Artifactory Secrets"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait
  - command: |
      gradle assemble artifactoryPublish
    label: "Build & Publish Library"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      gradle test
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"