steps:
  - command: |
      bash .scripts/artifactory.sh
      gradle assemble artifactoryPublish --stacktrace
    label: "Build & Publish Library"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: |
      bash .scripts/artifactory.sh
      gradle test
    label: "Run Tests"
    agents:
     - "queue=automation-android-builder-fleet"

  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
     - "queue=automation-android-builder-fleet"